import { z } from 'zod';

const zAction = z.union([
  z.literal('cPrevPage'),
  z.literal('cNextPage'),
  z.literal('sTopOfNavigationBar'),
  z.literal('cNavigationSelectorHomeTab'),
  z.literal('cNavigationBarHomeHomeChannel'),
  z.literal('cNavigationBarHomeTopUnreadChannel'),
  z.literal('cNavigationBarHomeBottomUnreadChannel'),
  z.literal('cNavigationSelectorChannelsTab'),
  z.literal('fNavigationBarChannelsChannelFilterInput'),
  z.literal('iCurrentChannelNameNavigationBarChannelsChannelFilter'),
  z.literal('cNavigationBarChannelsTopSearchResult'),
  z.literal('cNavigationBarChannelsChannelFilterStar'),
  z.literal('eNavigationBarChannelsTreeToCurrentChannel'),
  z.literal('cNavigationBarChannelsNextChannel'),
  z.literal('cNavigationBarChannelsPrevChannel'),
  z.literal('cNavigationBarChannelsCurrentChannelHash'),
  z.literal('sNavigationBarChannelsToCurrentChannel'),
  z.literal('cNavigationSelectorActivityTab'),
  z.literal('cNavigationBarActivityIsNotAllToggleButton'),
  z.literal('cNavigationBarActivityIsPerChannelToggleButton'),
  z.literal('tNavigationBarActivityFollowMode'),
  z.literal('cNavigationSelectorUsersTab'),
  z.literal('fNavigationBarUsersUserFilterInput'),
  z.literal('cNavigationBarUsersTopSearchResult'),
  z.literal('cNavigationSelectorClipTab'),
  z.literal('cHChannelNameParentChannelName'),
  z.literal('oVMessageListNextMessage'),
  z.literal('oVMessageListPrevMessage'),
  z.literal('sToBottomOfV'),
  z.literal('cVLatestMessageStampPicker'),
  z.literal('cV2ndLatestMessageStampPicker'),
  z.literal('cV3rdLatestMessageStampPicker'),
  z.literal('cV4thLatestMessageStampPicker'),
  z.literal('cV5thLatestMessageStampPicker'),
  z.literal('cV6thLatestMessageStampPicker'),
  z.literal('cV7thLatestMessageStampPicker'),
  z.literal('cV8thLatestMessageStampPicker'),
  z.literal('cV9thLatestMessageStampPicker'),
  z.literal('cVLatestMessageContextMenuRemovePin'),
  z.literal('cVLatestMessageContextMenuAddPin'),
  z.literal('cVLatestMessageContextMenuClipMessage'),
  z.literal('cVLatestMessageContextMenuEditMessage'),
  z.literal('cVLatestMessageContextMenuCopyLink'),
  z.literal('cVLatestMessageContextMenuEmbedMessage'),
  z.literal('cVLatestMessageContextMenuCopyMarkdown'),
  z.literal('cVLatestMessageContextMenuDeleteMessage'),
  z.literal('cVSelectedMessageContextMenuRemovePin'),
  z.literal('cVSelectedMessageContextMenuAddPin'),
  z.literal('cVSelectedMessageContextMenuClipMessage'),
  z.literal('cVSelectedMessageContextMenuEditMessage'),
  z.literal('cVSelectedMessageContextMenuCopyLink'),
  z.literal('cVSelectedMessageContextMenuEmbedMessage'),
  z.literal('cVSelectedMessageContextMenuCopyMarkdown'),
  z.literal('cVSelectedMessageContextMenuDeleteMessage'),
  z.literal('cVSelectedMessageSpoilers'),
  z.literal('cVSelectedMessageDetailButton'),
  z.literal('cVSelectedMessageStamps'),
  z.literal('fVMessageInput'),
  z.literal('cVMessageInputStampButton'),
  z.literal('cSidebarOpener'),
  z.literal('cSidebarCloser'),
  z.literal('cSidebarContentViewers'),
  z.literal('bActiveInputElement'),
  z.literal('lVAllMessages'),
  z.literal('sleep100ms'),
]);

export type ActionEnum = z.infer<typeof zAction>;

export default zAction;
