import { z } from 'zod';

const zAction = z.union([
  z.literal('cPrevPage'),
  z.literal('cNextPage'),
  z.literal('scrollTopOfNavigationBar'),
  z.literal('cNavigationSelectorHomeTab'),
  z.literal('cNavigationBarHomeHomeChannel'),
  z.literal('cNavigationBarHomeTopUnreadChannel'),
  z.literal('cNavigationBarHomeBottomUnreadChannel'),
  z.literal('cNavigationSelectorChannelsTab'),
  z.literal('fNavigationBarChannelsChannelFilterInput'),
  z.literal('inputCurrentChannelNameNavigationBarChannelsChannelFilter'),
  z.literal('cNavigationBarChannelsTopSearchResult'),
  z.literal('cNavigationBarChannelsChannelFilterStar'),
  z.literal('eNavigationBarChannelsTreeToCurrentChannel'),
  z.literal('cNavigationBarChannelsNextChannel'),
  z.literal('cNavigationBarChannelsPrevChannel'),
  z.literal('cNavigationBarChannelsCurrentChannelHash'),
  z.literal('scrollNavigationBarChannelsToCurrentChannel'),
  z.literal('cNavigationSelectorActivityTab'),
  z.literal('cNavigationBarActivityIsNotAllToggleButton'),
  z.literal('cNavigationBarActivityIsPerChannelToggleButton'),
  z.literal('toggleNavigationBarActivityFollowMode'),
  z.literal('cNavigationSelectorUsersTab'),
  z.literal('fNavigationBarUsersUserFilterInput'),
  z.literal('cNavigationBarUsersTopSearchResult'),
  z.literal('cNavigationSelectorClipTab'),
  z.literal('cChannelHeaderChannelNameParentChannelName'),
  z.literal('mouseoverChannelViewMessageListNextMessage'),
  z.literal('mouseoverChannelViewMessageListPrevMessage'),
  z.literal('scrollToBottomOfChannelView'),
  z.literal('cChannelViewLatestMessageStampPicker'),
  z.literal('cChannelView2ndLatestMessageStampPicker'),
  z.literal('cChannelView3rdLatestMessageStampPicker'),
  z.literal('cChannelView4thLatestMessageStampPicker'),
  z.literal('cChannelView5thLatestMessageStampPicker'),
  z.literal('cChannelView6thLatestMessageStampPicker'),
  z.literal('cChannelView7thLatestMessageStampPicker'),
  z.literal('cChannelView8thLatestMessageStampPicker'),
  z.literal('cChannelView9thLatestMessageStampPicker'),
  z.literal('cChannelViewLatestMessageContextMenuRemovePin'),
  z.literal('cChannelViewLatestMessageContextMenuAddPin'),
  z.literal('cChannelViewLatestMessageContextMenuClipMessage'),
  z.literal('cChannelViewLatestMessageContextMenuEditMessage'),
  z.literal('cChannelViewLatestMessageContextMenuCopyLink'),
  z.literal('cChannelViewLatestMessageContextMenuEmbedMessage'),
  z.literal('cChannelViewLatestMessageContextMenuCopyMarkdown'),
  z.literal('cChannelViewLatestMessageContextMenuDeleteMessage'),
  z.literal('cChannelViewSelectedMessageContextMenuRemovePin'),
  z.literal('cChannelViewSelectedMessageContextMenuAddPin'),
  z.literal('cChannelViewSelectedMessageContextMenuClipMessage'),
  z.literal('cChannelViewSelectedMessageContextMenuEditMessage'),
  z.literal('cChannelViewSelectedMessageContextMenuCopyLink'),
  z.literal('cChannelViewSelectedMessageContextMenuEmbedMessage'),
  z.literal('cChannelViewSelectedMessageContextMenuCopyMarkdown'),
  z.literal('cChannelViewSelectedMessageContextMenuDeleteMessage'),
  z.literal('cChannelViewSelectedMessageSpoilers'),
  z.literal('cChannelViewSelectedMessageDetailButton'),
  z.literal('cChannelViewSelectedMessageStamps'),
  z.literal('fChannelViewMessageInput'),
  z.literal('cChannelViewMessageInputStampButton'),
  z.literal('cSidebarOpener'),
  z.literal('cSidebarCloser'),
  z.literal('cSidebarContentViewers'),
  z.literal('bActiveInputElement'),
  z.literal('mouseleaveChannelViewAllMessages'),
  z.literal('sleep100ms'),
]);

export type ActionEnum = z.infer<typeof zAction>;

export default zAction;
