type SelectorEnum =
  // NavigationBar
  /// Popup
  | 'popupNavigator'
  | 'previousPage'
  | 'nextPage'
  /// Homeタブ
  | 'navigationSelectorHomeTab'
  | 'navigationBarHomeHomeChannel'
  | 'navigationBarHomeTopUnreadChannel'
  /// Channelsタブ
  | 'navigationSelectorChannelsTab'
  | 'navigationBarChannelsChannelFilterInput'
  | 'navigationBarChannelsChannelFilterStar'
  | 'navigationBarChannelsChannelList'
  | 'navigationBarChannelsChannelSelectedChannel'
  | 'navigationBarChannelsChannelSelectedChannelHash'
  /// Activityタブ
  | 'navigationSelectorActivityTab'
  | 'navigationBarActivityIsNotAllToggleButton'
  | 'navigationBarActivityIsPerChannelToggleButton'
  | 'navigationBarActivityLatestMessage'
  /// Usersタブ
  | 'navigationSelectorUsersTab'
  | 'navigationBarUsersUserFilterInput'
  /// Clipタブ
  | 'navigationSelectorClipTab'
  // ChannelView
  | 'channelHeaderChannelName'
  | 'channelViewMessageList'
  | 'channelViewLatestMessage'
  | 'channelView2ndLatestMessage'
  | 'channelView3rdLatestMessage'
  | 'channelView4thLatestMessage'
  | 'channelView5thLatestMessage'
  | 'channelView6thLatestMessage'
  | 'channelView7thLatestMessage'
  | 'channelView8thLatestMessage'
  | 'channelView9thLatestMessage'
  | 'channelViewMessageToolStamp'
  | 'channelViewMessageToolDots'
  | 'channelViewContextMenuList'
  | 'channelViewContextMenuRemovePin'
  | 'channelViewContextMenuAddPin'
  | 'channelViewContextMenuClipMessage'
  | 'channelViewContextMenuEditMessage'
  | 'channelViewContextMenuCopyLink'
  | 'channelViewContextMenuEmbedMessage'
  | 'channelViewContextMenuCopyMarkdown'
  | 'channelViewContextMenuDeleteMessage'
  | 'channelViewMessageInput'
  | 'channelViewMessageInputStampButton'
  // SideBar
  | 'sidebarOpener'
  | 'sidebarCloser'
  | 'sidebarContentViewers';
