type SelectorEnum =
  // NavigationBar
  /// Popup
  | "previousPage"
  | "nextPage"
  /// Homeタブ
  | "navigationSelectorHomeTab"
  | "navigationBarHomeHomeChannel"
  | "navigationBarHomeTopUnreadChannel"
  /// Channelsタブ
  | "navigationSelectorChannelsTab"
  | "navigationBarChannelsChannelFilter"
  /// Activityタブ
  | "navigationSelectorActivityTab"
  /// Usersタブ
  | "navigationSelectorUsersTab"
  /// Clipタブ
  | "navigationSelectorClipTab"
  // MainView
  // SideBar
  | "sidebarOpener";
